In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("50_Startups.csv")

In [3]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [5]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]

In [6]:

independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0      165349          136897           471784              0               1
1      162597          151377           443898              0               0
2      153441          101145           407934              1               0
3      144372          118671           383199              0               1
4      142107           91391           366168              1               0
5      131876           99814           362861              0               1
6      134615          147198           127716              0               0
7      130298          145530           323876              1               0
8      120542          148718           311613              0               1
9      123334          108679           304981              0               0
10     101913          110594           229160              1               0
11     100671           91790           249744              0               0
12      93863          127320           249839              1               0
13      91992          135495           252664              0               0
14     119943          156547           256512              1               0
15     114523          122616           261776              0               1
16      78013          121597           264346              0               0
17      94657          145077           282574              0               1
18      91749          114175           294919              1               0
19      86419          153514                0              0               1
20      76253          113867           298664              0               0
21      78389          153773           299737              0               1
22      73994          122782           303319              1               0
23      67532          105751           304768              1               0
24      77044           99281           140574              0               1
25      64664          139553           137962              0               0
26      75328          144135           134050              1               0
27      72107          127864           353183              0               1
28      66051          182645           118148              1               0
29      65605          153032           107138              0               1
30      61994          115641            91131              1               0
31      61136          152701            88218              0               1
32      63408          129219            46085              0               0
33      55493          103057           214634              1               0
34      46426          157693           210797              0               0
35      46014           85047           205517              0               1
36      28663          127056           201126              1               0
37      44069           51283           197029              0               0
38      20229           65947           185265              0               1
39      38558           82982           174999              0               0
40      28754          118546           172795              0               0
41      27892           84710           164470              1               0
42      23640           96189           148001              0               0
43      15505          127382            35534              0               1
44      22177          154806            28334              0               0
45       1000          124153             1903              0               1
46       1315          115816           297114              1               0
47          0          135426                0              0               0
48        542           51743                0              0               1
49          0          116983            45173              0               0

In [7]:
dependent=dataset[['Profit']]

In [8]:
dependent

    Profit
0   192261
1   191792
2   191050
3   182901
4   166187
5   156991
6   156122
7   155752
8   152211
9   149759
10  146121
11  144259
12  141585
13  134307
14  132602
15  129917
16  126992
17  125370
18  124266
19  122776
20  118474
21  111313
22  110352
23  108733
24  108552
25  107404
26  105733
27  105008
28  103282
29  101004
30   99937
31   97483
32   97427
33   96778
34   96712
35   96479
36   90708
37   89949
38   81229
39   81005
40   78239
41   77798
42   71498
43   69758
44   65200
45   64926
46   49490
47   42559
48   35673
49   14681

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
X_train

array([[ 1.17644918,  0.84516741,  0.94354831,  2.        , -0.76870611],
       [ 0.964209  ,  1.27283753,  0.42738466,  2.        , -0.76870611],
       [-1.47369376,  0.01533133, -1.52350767, -0.5       ,  1.30088727],
       [-1.48308111, -2.79556033, -1.53808904, -0.5       ,  1.30088727],
       [-0.14952413,  1.13638837, -0.71716479, -0.5       ,  1.30088727],
       [ 0.85311854, -0.04433364,  0.46771904, -0.5       ,  1.30088727],
       [-0.22353662, -0.31509692, -0.83981534,  2.        , -0.76870611],
       [-0.19455471,  0.21198893, -1.18497162, -0.5       , -0.76870611],
       [ 0.10479514, -0.08389031,  0.48741117, -0.5       , -0.76870611],
       [-1.00965537, -1.07020622, -0.40405994, -0.5       , -0.76870611],
       [ 0.06872149, -0.38396202,  0.75036622, -0.5       , -0.76870611],
       [-1.17639355,  0.14067823, -1.26581662, -0.5       ,  1.30088727],
       [ 0.97648634,  0.96892273,  0.84958544, -0.5       ,  1.30088727],
       [ 0.39131425,  0.45561766,  0.3979001 , -0.5       , -0.76870611],
       [-0.16881124,  0.6131456 , -0.48098184, -0.5       , -0.76870611],
       [ 1.20879249, -0.92948696,  1.24226335, -0.5       ,  1.30088727],
       [ 0.44593715,  0.82758236,  0.6270797 , -0.5       ,  1.30088727],
       [-0.9048368 , -0.20232741, -0.2140807 , -0.5       , -0.76870611],
       [-1.49419016, -0.26300168, -1.19195964, -0.5       , -0.76870611],
       [ 1.83846226,  1.07214274,  1.86319372, -0.5       , -0.76870611],
       [ 0.42966301,  0.13827145,  0.37625408,  2.        , -0.76870611],
       [-0.59093451, -2.81341712, -0.02839235, -0.5       , -0.76870611],
       [ 0.08493413, -0.95017754, -0.46096789, -0.5       ,  1.30088727],
       [ 1.26493212,  0.90991769, -0.55948984, -0.5       , -0.76870611],
       [-0.11002758, -0.69901791,  0.79713695,  2.        , -0.76870611],
       [-0.90670197,  0.1280232 ,  0.00300012,  2.        , -0.76870611],
       [ 0.11250179,  1.16515333,  0.75858788, -0.5       ,  1.30088727],
       [ 0.27708784,  1.15509918, -1.53808904, -0.5       ,  1.30088727],
       [ 1.03371228, -0.58535556,  0.79876902, -0.5       , -0.76870611],
       [-0.70389014, -1.58289019, -0.19719297, -0.5       , -0.76870611],
       [-1.4672374 , -0.30830358,  0.73848965,  2.        , -0.76870611],
       [ 1.46491545, -0.19747502,  1.39809935, -0.5       ,  1.30088727],
       [ 1.89486834,  0.51004205,  2.07686481, -0.5       ,  1.30088727],
       [-1.49419016,  0.45293914, -1.53808904, -0.5       , -0.76870611],
       [-1.03964159,  1.20525347, -1.32098523, -0.5       , -0.76870611]])

In [12]:
from sklearn.svm import SVR
regressor=SVR(kernel="poly",C=10000.0)
regressor.fit(X_train,Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=10000.0, kernel='poly')

In [13]:
y_pred=regressor.predict(X_test)

In [14]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [15]:
r_score

0.8129635349114983

In [16]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34], dtype=int32)

In [17]:
'''rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))'''

R&D: 987512
Admin 785641
Marketing  85462
State_flo 0 or 1: 0
State_new 0 or 1: 1

In [55]:
#result=regressor.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

In [56]:
#result

array([6.14214238e+20])

In [18]:
import pickle
fileName="final_SVM_2_Model.sav"
pickle.dump(regressor,open(fileName,'wb'))

In [19]:
load_model=pickle.load(open("final_SVM_2_Model.sav",'rb'))

In [20]:
rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))

R&D: 874562
Admin 874512
Marketing  845694
State_flo 0 or 1: 0
State_new 0 or 1: 1

In [21]:
result=load_model.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

In [22]:
result

array([7.20595991e+21])